### ISSUE TITLE
[Function] User selects redo button to restore the most recently removed change

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#1]
# Criteria

Given that User has selected the `undo` button to remove a drawing action, they can select the `redo` button to restore that most recently removed change. User can continue to select `redo` from the most recently removed to the last removed action. 

## Tasks
- [x] selecting `redo` restores most recently removed
- [x] continues to restore up to the last removed action
- [x] ensure it behaves well on mobile
