### ISSUE TITLE
[Function] User can download image to their device

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#10]
# Criteria
Given has completed a choodle and wants to download the image to their device, so they can share it. A download button on the canvas should trigger the image download

## Tasks
- [x] `download` button on the canvas screen (use same placeholder UI)
     * top row - left: download, right: clear
     * bottom row - left: undo, right: redo
- [ ] user can download image to their device
- [ ] determine file name for the download. 'choodle' to start
