### ISSUE TITLE
View page: As a user, I see a styled view page after selecting `done` on the canvas

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#103]
# Criteria
Given the user selected the `done` button on the canvas, they are directed to a styled view page.

## Tasks
- [x] two text boxes (these should be editable via CMS in #104)
- [x] top text box should now be the choodle [logo](https://www.notion.so/rmxparty/Wordmark-ede7b16388bf46d18965bde08e202ecb?pvs=4)
- [x] choodle image with shadow
- [x] reset canvas button: "Draw"
- [x] send button
- [x] yellow background
- [x] Icons: In [Notion](https://www.notion.so/rmxparty/App-icons-780defb253cb4ac39e4054c2c8e40e47?pvs=4)
- [x] top content block: `margin-top: 0px` (see comments below)

## Design Reference
See [Figma](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=913-282090&mode=design&t=3NHmgVBZ9qC2JILr-11)

![Image](https://github.com/rmx-party/choodle/assets/71292601/86d7a337-1654-43ac-b1cb-ff8e94b1c6a5)
