### ISSUE TITLE
As a user, I see a Welcome page with a button, so that I can enter the drawing experience

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#105]
# Criteria
Given [x], then [y]

## Tasks
- [ ] [wordmark](https://www.notion.so/rmxparty/Wordmark-ede7b16388bf46d18965bde08e202ecb?pvs=4)
- [ ] tagline
- [ ] connect tagline to Sanity CMS
- [ ] [background graphics](https://www.notion.so/rmxparty/Welcome-graphics-a7901afdfe9d45f6bf92f644e1219658?pvs=4)
- [ ] `Let's Draw` button (icon can be exported from Figma

## Design Reference
[View design in Figma ↗ ](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=748-223916&mode=design&t=MOENQONfgFFHW1Y6-4)

![Image](https://github.com/rmx-party/choodle/assets/71292601/f49a781c-85fd-467c-ab29-e2b128a5e3cd)
