### ISSUE TITLE
Canvas: As a user, I want to see canvas ui updates, so I can complete my choodle

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#106]
# Criteria
Given the following updates to the canvas page, adjustments are needed. Refer to the designs

## Tasks
- [x] prompt bar at the top, with shadow treatment
- [x] canvas ratio change: 3:4 ratio
- [x] canvas shadow treatment (meant to look a bit like paper)
- [x] yellow buttons should be on the bottom of the screen, visible above the nav bar

## Design Reference
[View design in Figma ↗](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=944-342561&mode=design&t=A5K3uBHFZZH9UVXl-11)

![Image](https://github.com/rmx-party/choodle/assets/71292601/14ab6d2e-292a-49c5-8719-ad2596257f47)
