### ISSUE TITLE
As a user offline, I want a snapshot saved, so I can save it when I'm back online

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#109]
# Criteria
Given that the user is offline and selects `done` button, they cannot save their choodle in real time. we want a way to save a snapshot on the background so that their image can be saved later, when they are back online.

## Tasks
- [ ] saving image(s) in the background
- [ ] when user selects done, we save a snapshot
- [ ] messaging to communicate the user is offline
    * "it'll get saved when you're back online"
- [ ] when user is back online, the last image gets saved
