### ISSUE TITLE
User can send a choodle to their friend directly from the canvas (without mint)

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#11]
# Criteria
Given User has completed a choodle and wants to send it to a friend, User can select `send` and it will directly open native options to send an image of the choodle. User should then receive it.

_Notes:_
* this feature does not require minting capabilities
* prioritize enabling native functionality as much as possible
* at first pass, hide the share button for browsers that do not support native sharing API
* start with iPhone os behavior models as a north star

## Tasks
- [x] `send` button on the canvas screen
- [x] enable native sharing functionality
- [ ] validate receipt of share
- [ ] placeholder title/description for the share

## Design Reference
**examples of iPhone native sharing ui**
![image](https://github.com/rmx-party/choodle/assets/71292601/c8a99323-5c33-4f4a-91f0-48586371cc4b)![IMG_2736](https://github.com/rmx-party/choodle/assets/71292601/ac28ce8d-7faf-4f59-a21c-524890027178)
