### ISSUE TITLE
As a user, I want to view an FAQ page, so I can learn more about choodle

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#113]
# Criteria
Given there is an FAQ page made in Notion. It should be a live page that we can direct users to from the webapp

## Tasks
- [x] publish [Notion page] when ready: 
    * link https://rmxparty.com/choodlefaq
    * direction notion link: https://rmxparty.notion.site/Choodle-FAQ-f2f50cf66a484ee79f9d5657d6c0e7d1?pvs=4
- [x] point webapp to [Notion page](https://www.notion.so/rmxparty/Choodle-FAQ-f2f50cf66a484ee79f9d5657d6c0e7d1?pvs=4)
- [x] add link to the FAQs on the app: landing page
