### ISSUE TITLE
As a user, I want to view a landing page, so I see 'welcome' and 'how to' are combined

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#121]
# Criteria
Given the `how to` page is converted into the landing page

## Tasks
- [x] remove `welcome` screen
- [x] adjust new landing (how to) page per design
- [x] primary button: should be white with drawing icon (contrast with yellow bkg)
- [x] second copy block below CTA button
- [x] connect copy block to Sanity CMS
- [x] hard code 'FWB Fest 2023' and stars below logomark, per design

## Design Reference
[Figma](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=920-345503&mode=design&t=3NHmgVBZ9qC2JILr-11)
