### ISSUE TITLE
As a user, I see updated canvas page UI, so I can draw and submit above the fold

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#122]
# Criteria

## Tasks
- [x] prompt bar at top
- [x] buttons on the bottom
- [x] canvas ratio adjustment (TBD: 3:4 ratio)
- [x] canvas styling treatment to see bordline

## Design Reference
[figma
](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=944-279326&mode=design&t=A5K3uBHFZZH9UVXl-11)
