### ISSUE TITLE
[Epic] Mint FWBFest Choodles

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#140]
# Criteria
Given all choodles that were made during FWB Fest (that aren't tests or inappropriate), they should be minted in a collection, 100% onchain.

## Tasks
- [x] using: Polygon
    * a way to get back in touch with Polygon team
- [x] store 100% onchain, no dependencies
- [x] wallet: use ledger (RMX wallet)
- [x] start with requested mints: do manually (@anothermadeline to deliver list of requested choodles to mint)
- [x] mint all choodles made during FEST: exclude tests and inappropriate images
- [x] 1 of 1 NFTs
- [x] Metadata #141

## Questions
* are we doing anything re: user IDs?

## Design Reference
Sanity: https://choodle-sanity-studio.vercel.app/desk/choodle

**Comment by brandondees** [comment]
@rmx-party/contributors minting has been done for the scope of FWB FEST, and I'm caught up on airdrop requests for the 4 addresses we have received so far. Let's call this done and make new tickets for additional requests so we can track them easily.

**Comment by paigel** [comment]
absolutelyyy. Thank you for tracking so much within this — it wasn't the intention, but gravity took the wheel 😅

Thank you!! ✅✅✅
