### ISSUE TITLE
NFTs: As a dev, I need to input custom metadata for the contract and opensea

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#141]
# Criteria
Given #140 we are minting a collection of FWBFest Choodles, the contract and opensea account will need metadata:

See [Notion](https://www.notion.so/rmxparty/Metadata-for-FWB-Choodle-collection-62b59659f3fb4516b5dc7d58974fd5e1?pvs=4)

## Tasks
- [ ] ascii: choodle-branded [In Notion](https://www.notion.so/rmxparty/ASCII-ef744dd780c8494c945af3cfb98ff74c?pvs=4)
- [ ] title: `Choodle FEST [000]`
- [ ] Collection title: `Choodle FEST`
- [ ] Collection description: ```Choodle is a lo-fi mobile drawing app that creates fully onchain media.

This collection of Choodles was made by attendees who participated in our private beta at FWB FEST 2023.

We're building super simple tools to help a broad audience of consumers express their creativity onchain. Join our mission to help creators to own, not rent, the culture they create on the internet: choodle.xyz```

**OpenSea data**
- [ ] Category: art
- [ ] no custom tags atm

## Design Reference
[add image, video, or link when applicable]
