### ISSUE TITLE
Automate prompts: As admin, a prompt should auto-publish so users see a new one per day

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#143]
# Criteria
Given a list of prompts in Sanity (https://choodle-sanity-studio.vercel.app/desk/dailyPrompt), there should be a new prompt publishing live once per day.

## Tasks
- [ ] determine time when new prompt is published: e.g. 12am et (or local time?)
- [ ] prompt publishes from a given ordered list
- [ ] no prompt is published twice: (likely to be managed by the list)
- [ ] admin should be able to manually arrange the order of the prompt list
- [ ] prompts should display in sentence case — tbd if that should be coded in
