### ISSUE TITLE
Answer questions about gas limits and calculation

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#15]
## Criteria

Open questions transferred from Issue #9

Storage currently works but data is being lost on the way to transaction. In order to address the problem, further investigation is required. 

## Tasks
Find *actionable* answers to the following questions. If investigations exceed any reasonable amount of time, abandon and return to team to find a more efficient path forward. 

- [ ] What is the upper limit on data storage size?
- [ ] Whats the max. transaction size or gas limit?
- [ ] How is gas estimation system working?
