### ISSUE TITLE
Modal Functions: As a user I want to enter my email so I can get a certificate

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#157]
# Criteria
After a user selects `done` on canvas, a modal appears before [over] the view page. This modal prompts user to input their email address to receive a "Choodle Certificate"

We would like the copy of the modal to be hooked up to sanity CMS for editing.

Start with this library: https://micromodal.vercel.app/ | https://github.com/Ghosh/micromodal

## Tasks
_This is to confirm the functionality user actions for and within the modal. Styling will be completed in a separate ticket: #162_
- [x] modal appears over canvas
- [x] closing modal goes to canvas
- [x] selecting `no thanks` goes to view page
- [ ] email input: include all standard email input states
    - [x] default
    - [x] error
    - [ ] success
- [x] `certify!` button: submits email address and triggers certificate to be made & emailed
    * user then goes to view page
- [x] copy block below image is hooked up to Sanity CMS for editing

## Design Reference
**Refer to wires**
[in Figma](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=83%3A60969&mode=design&t=njsooH0di9NMHJ7a-1)

**User Flow**
![Image](https://github.com/rmx-party/choodle/assets/120132882/006ff761-ce7e-42c8-bbea-52a2090941fa)

**Comment by paigel** [comment]
https://micromodal.vercel.app/

**Comment by paigel** [comment]
a couple things we'll need for minimum viable modal function:
- [ ] scroll mobile content if below the fold
    * for iphones: content is getting cut off BTF and under the nav bar, but I'm not able to scroll to make the content visible
- [ ] feedback in the input box when email address is submitted `true`
    * check mark or "success!" msg

**Comment by paigel** [comment]
@brandondees the modal is not always popping up for me; sometimes when I select `done` it takes me directly to the viewpage

**Comment by brandondees** [comment]
@paigel once you've saved email it will re-use it each time, i had assumed that's desirable for now but we can revisit those decisions / add more control. did you get the email though?

if you need to reset the email, it's stored in the browser local storage so if you clear that it'll go back to prompting

**Comment by paigel** [comment]
ahhh @brandondees I tested a fake email and it seemed to have accepted it. 
I mostly want to keep seeing it for testing without having to keep clearing storage. I will use private browser for now.

* & I have not gotten any emails

**Comment by brandondees** [comment]
@paigel the modal is set up to scroll if it overflows, but i forgot about the safari overlay bar, I guess we'll just have to set a bottom padding on it to ensure theres's blank space to scroll to. that'll mean it'll be scrollable unnecessarily on some other viewports but oh well.

on the input feedback, we might have to get into a more visual example of what you mean. i kinda assumed there's no extra interaction step needed since it'll close instantly on submit and doesn't come up again while it's stored (for now).

**Comment by brandondees** [comment]
@paigel yeah it'll be handy to add a flag to the url to always show it or something like that, let me get back to you. also we might have the need for a "account info/settings" type page somewhere at this point. we can talk about how to prioritize that next week.

**Comment by brandondees** [comment]
also @paigel be careful to only use @example.com for fake/placeholder email input, it's designated for testing purposes etc but otherwise we might be spamming random inboxes and get filtered based on that.

**Comment by paigel** [comment]
sounds good! Let's revisit all this together on Monday

**Comment by paigel** [comment]
adding note for monday discussion:
* height/width constraints in larger viewports

**Comment by paigel** [comment]
currently debugging getting the certificate email sent to users upon submitting their email addresses: 
solution: use the image in sanity to render a lowres thumbnail within the email along with a link to the certificate — will try this first
