### ISSUE TITLE
[Pair] Implement post-mint NFT page

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#16]
## Criteria

Add a simple, markdown (no ui-stylization) page for post-mint experience. 

## Tasks

Page should include:

- [x] link to view minted Choodle NFT on Opensea
- [x] link to return to Choodle canvas
- [x] link to magic wallet 
- [x] image render of the minted Choodle (resized in container to fit reasonably on the page) (center-aligned)
- [x] remove Choodle canvas menu buttons (Undo, Redo, etc) from this page\
- [x] include permalink URL Also see #6
