### ISSUE TITLE
Certificate: As eng, I want to autofill content into the COA per user instance

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#161]
# Criteria
Given a user submits an email address in modal #157 to "certify ownership" of their choodle, specific user content should autofill into the Certificate of Authenticity (COA) that will be emailed to said user.

## Tasks
**Content to fill:**
- [x] "created by" = email address
- [x] "Made on" = timestamp of when choodle was created
- [x] choodleID = slug from "View" page
- [x] "Creator" = email address

**Assets to include:**
- [x] frame
- [x] golden seal
- [x] QR code – to link to "View" page per Choodle
- [x] Choodle image render
- [x] arrow pointing rightwards (added to asset library 8/24)
- [ ] font: [DejaVu Sans](https://dejavu-fonts.github.io/)

SVGs and PNGs of assets, if helpful, can be found in the [Choodle Asset Library ↗](https://www.notion.so/rmxparty/CoA-Assets-03417868960342028e2299c05b012cdc?pvs=4) 

## Design Reference
- [Blank Cert – Bounding Boxes Shown](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=104-68144&mode=design&t=KWHqEujZXL1Eyb0R-11)
- [Blank Cert – Text Fields Empty](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=104-67844&mode=design&t=KWHqEujZXL1Eyb0R-11)
- [Blank Cert – Assets Only](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=125-63735&mode=design&t=Y4FOWySvOeNY4sVq-11)
- [Filled Cert – Longest Email Address](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=104-67272&mode=design&t=KWHqEujZXL1Eyb0R-11)
- [Filled Cert – Longer Email Address](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=104-66986&mode=design&t=KWHqEujZXL1Eyb0R-11)
- [Filled Cert – Standard Email Address](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=104-67558&mode=design&t=KWHqEujZXL1Eyb0R-11)

**Comment by anothermadeline** [comment]
@anothermadeline to send "blank" with no text, no image

**Comment by anothermadeline** [comment]
added `Blank Cert – Assets Only` to [Figma](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=125-63735&mode=design&t=Y4FOWySvOeNY4sVq-11)

also added arrow pointing rightwards to [asset library](https://www.notion.so/rmxparty/Certificate-of-Authenticity-CoA-Assets-03417868960342028e2299c05b012cdc?pvs=4#812c79ca2f1644f6aab8466bdf6eff5b)

**Comment by paigel** [comment]
notes per slack:
- [ ] include `ChoodleID` below the QR code
- [ ] add `™` to 'Certificate' on the heading. to read: "Certificate™ of Ownership"

**Comment by paigel** [comment]
deferring custom font at this stage
