### ISSUE TITLE
Email setup: As a user, I receive an email right away so I can view my certificate

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#163]
# Criteria
Given the user has submitted their email address and the certificate is populated #161 , user receives an email with their completed certificate. The email has a prepopulated subject line and body copy, along with their custom certificate image.

This email should be sent to the user immediately after they submit their email address.

Note: email tests were sent to Dees & Steven emails (August 23, 2023)

QUESTION: can any of this content be set up in Sanity? please see #152 

## Tasks
- [x] email subject line
- [x] add certificate image inline at the beginning of the email, above the copy content.
- [x] body copy: templated copy with custom info auto-filled, same as the certificate
- [x] confirm all links work
    * link to viewpage
    * link to choodle.xyz
    * link to rmx.party
- [x] text style should default to system san serif
- [x] email should be automagically sent right after user submits their email address into modal #157 
- [ ] nice to have: user can save the png with an evergreen link (accessible via Sanity)

## Design Reference
**Source of Truth for Copy**
[in Notion](https://www.notion.so/rmxparty/Copy-Email-Certificate-of-Authenticity-174c18bc24b446cf82ab0d6a17dca029?pvs=4)

**Example of email design**
[in Figma](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=103%3A66474&mode=design&t=njsooH0di9NMHJ7a-1)

**Comment by paigel** [comment]
there's a bug preventing the image to load in email. It is crashes in vercel, but not locally

**Comment by paigel** [comment]
for gmail, the file is too large to show in-line. Hooked it up to sanity and so there's a couple options:
* link to the certificate image in the email
* use the image in sanity to render a lowres thumbnail within the email along with a link — will try this first

**Comment by paigel** [comment]
Question re: receiving the email —
Is there a way for the sender of the Certificate emails (help@rmx.party)to read as their name, 'RMX Party,' instead of 'help@rmx.party.'

In tests, the sender shows as 'RMX Party,' but for the actual receipts the sender shows as 'help@rmx.party' or 'help'

See images for comparison.
* gmail desktop



![Image](https://github.com/rmx-party/choodle/assets/71292601/11dd7061-f30f-4263-ad0d-21a8289340ee)
![Image](https://github.com/rmx-party/choodle/assets/71292601/e4d58c62-35dd-4e56-8807-af3f54796478)



* iphone mail app
![Image](https://github.com/rmx-party/choodle/assets/71292601/a758b608-44f6-43c5-9fb8-715e8ddea9a9)
![Image](https://github.com/rmx-party/choodle/assets/71292601/d24b1a40-076e-4026-a8c9-7b8a8c231c40)

**Comment by brandondees** [comment]
@paigel just pushed something that should address the sender name

**Comment by paigel** [comment]
sender name is displaying. thank you!On Aug 28, 2023, at 6:35 PM, Brandon Dees ***@***.***> wrote:﻿
@paigel just pushed something that should address the sender name

**Comment by paigel** [comment]
Loading screen now takes longer to allow for backend communication and the email to be sent immediately upon loading the view page. We may want to revisit solutions to reduce load time in the future.

This is approved. Getting the email right away is soo great!
