### ISSUE TITLE
Build single-page landing with email capture for choodle.xyz

### ISSUE THREAD

**Issue by anothermadeline** [rmx-party/choodle#19]
## Criteria

choodle.xyz  • [View design in Figma](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=191-6170&mode=design)

A simple, single-page landing with an link out to Google Form email capture will serve as a marketing stop-gap and funnel for collecting potential beta testers and interested users.

The design consists of an image, hyperlinks, and footer copyright. All page elements are centered and asset dimensions should not change based on screen resolution or viewport size. 

## Tasks
- [ ] Implement Choodle logotype and mascot (single image) `Choodle–Logo.svg`
- [ ] Add`Join Waitlist` with linkout to https://forms.gle/P6mHbxCyzvieE7gY8 (opens in new tab)
- [ ] Add footer copyright with linkout to rmx.party (no hyperlink styling)
- [ ] Ensure design remains centered, dimensions preserved

## Assets
![Image](https://user-images.githubusercontent.com/120132882/250104541-22291624-e431-412a-b69a-9c65fb93dab8.svg)
