### ISSUE TITLE
Set up Magic Connect: User logs in via Magic

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#2]
# Criteria
Given User selects `mint`, they are directed to connect a wallet address via Magic.

https://magic.link/docs/connect/overview

## Tasks
- [x] user sees page to "log in"
- [x] user can log in with email
- [x] user connects via magic link
- [ ] user returns to choodle.xyz connected via wallet

## Reference
starting point: implement magic connect as we did for **hello world hack**
_video: 00:00s - 00:40s_
https://github.com/rmx-party/choodle/assets/71292601/2a05112f-396f-4fc5-84b1-956e720920bb
