### ISSUE TITLE
[Function] User can mint their choodle

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#3]
# Criteria
Given User is connected and has a doodle (not a clear canvas), they can mint their doodle. User must select `mint` button on the canvas to prompt this mint flow.

_Note:_ This would be an immediate prompt after #2 : 
user doodles > selects `mint` > connects wallet > mints doodle

## Tasks
- [x] after magic connect, user is prompted to mint, "save permanently"
- [x] user sees transaction cost, fees, and total
- [x] user confirms the transaction
- [x] user sees confirmation screen
- [x] user sees screen of transaction in process
- [x] user goes back to choodle interface

## Design Reference
* https://cent.co/ — on mobile
* as a starting point: set up minting as we did for **hello world hack**
_video: 00:45s - 01:17s_

https://github.com/rmx-party/choodle/assets/71292601/f1071e22-42fe-4a19-9b58-6ffd40f4431e
