### ISSUE TITLE
Set fixed pixels for canvas

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#34]
# Criteria
Set the constraint of fixed pixels with a 9:16 ratio. 

## Tasks
- [ ] set pixels to start
- [ ] reference largest iPhone
    * iPhone 14 Pro Max: 430x932 pt (1290x2796 px @3x)
- [ ] set to 9:16 ratio of minimal pixel size
- [ ] assess possible adjustments
- [ ] review image quality
- [ ] remove anti-aliasing from canvas
