### ISSUE TITLE
Remove grayscale & appearance of blur while drawing

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#40]
# Criteria
When user is drawing on the canvas, the lines should not appear blurry or gray. Remove or minimize grayscale on the lines. Drawing should reflect minted output with highest fidelity possible. 

## Tasks
- [ ] to check first: can we remove grayscale altogether (browser might be automatically doing it)
- [ ] refresh canvas drawing right after user lifts finger
- [ ] implement blitting to reduce flicker (_might_ be that we don't have to do it)
