### ISSUE TITLE
Loader screen before post-mint page

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#44]
# Criteria
After user confirms mint and is awaiting the mint to complete, they should see a loader screen before the post-mint page. The post-mint page should only load once with no content loading delays.

## Tasks
- [x] add loader screen
- [ ] trigger screen after user selects `confirm` on magic
- [ ] load post-mint page only when all content is ready (clean transition)

## Design Reference
loader screen design to be provided
