### ISSUE TITLE
[Bug] App load failure

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#46]
# Criteria
Initial page/app load fails and requires a manual reload pretty often. this should also have error catching and retry logic

## Tasks
first try after-page-load event.
- [x] implement auto reload till the app fully loads
- [ ] add error-catching
- [ ] add retry logic
- [x] determine if this requires a loader screen for smoother ux
