### ISSUE TITLE
As a PM, I want to see specific analytics, so I can track KPIs

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#50]
# Criteria
Set up basic Vercel analytics package to enable standard usage data.

## Tasks
- [x] Set up vercel analytics
- [x] Set up Google Analytics: https://tagmanager.google.com/#/container/accounts/6139134545/containers/136998705/workspaces/2
    * Log into GA: http://analytics.google.com/analytics/web/
    * See Google Tag scripts in the comments below
- [ ] Comment here what the basic package includes
    - [ ] If needed, pair with product team to determine which items to enable
- [ ] Assess and identify additional features required for MVP analytics

### Notes on measurements to start:
_source of truth: tracking via [Choodle Product in Notion](https://www.notion.so/rmxparty/Choodle-Product-28bd8c58c3c04380880725edc557853c?pvs=4#5ddcb8f4a1e4444fbacc8c4528702910)_
- wallet address account
- wallet balance
- what they used to login (email, google, etc.)
- device?
- browser?
- count daily active users
    - over time
    - how many are returning users
- run timers: track time inside workflow
   - end-to-end
   - in canvas only
   - in mint flow
- count button clicks
- real-time user stats (tbd what that would inform)
- count link shares
- count external link clinks (how many accessed via a shared link)
- count mint %: how many mint/draw
- did users abandon? 
    - where did they drop off (in canvas, before/during mint)
- size of choodles
    - minted vs. non-minted
