### ISSUE TITLE
Loader: As a user, I need a screen to show me the app is busy, so that I wait

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#52]
# Criteria

**Solution**
Add a general loading screen as a global component, to utilize between page loads as-needed. Some screens will have custom copy. 

Where in the app should the loading state appear?
- anywhere we are waiting for something to load
- all sanity content will need this
- all file-saving actions will need this

## Tasks
~- [ ] [Choodle-Bob](https://www.notion.so/rmxparty/Choodle-Bob-aa1ea7f3e4e448be8f27bec6f716369d?pvs=4#8fc49a9931b140f1b7c24ce40137c671) with [Blinking Stars](https://www.notion.so/rmxparty/Welcome-graphics-a7901afdfe9d45f6bf92f644e1219658?pvs=4)~
- [x] default copy: ```enhancing happiness...```
- [ ] copy block that would be customized for some screens
- [x] v1: static: [see figma](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=931-364921&mode=design&t=j5WaWWtfZySrRLWO-11)
- [x] v2 (nice to have): add animated ellipses `...` to copy [(see prototype)](https://www.figma.com/proto/wozIImqVXBLj3XbQH4tqCw/Choodle?page-id=821%3A426078&type=design&node-id=821-428894&viewport=405%2C448%2C0.3&t=p5up3aeopnLroqiF-1&scaling=min-zoom&starting-point-node-id=821%3A426079&mode=design)

## Design Reference
See [Figma](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=931%3A365087&mode=design&t=j5WaWWtfZySrRLWO-1)

V1 Static: [See here](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=931-364921&mode=design&t=j5WaWWtfZySrRLWO-11)
V2 Prototype: [Ellispes](https://www.figma.com/proto/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=821-426078&viewport=630%2C508%2C0.2&t=j5WaWWtfZySrRLWO-0&scaling=scale-down&starting-point-node-id=931%3A364945&show-proto-sidebar=1)
V3 Prototyps: [Stars & ellipses](https://www.figma.com/proto/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=821-426078&viewport=630%2C508%2C0.2&t=j5WaWWtfZySrRLWO-0&scaling=scale-down&starting-point-node-id=821%3A426079&show-proto-sidebar=1)

![Image](https://github.com/rmx-party/choodle/assets/120132882/fc880ffb-e90b-4116-ba62-52ea91dfa77c)
