### ISSUE TITLE
Error handling 500s: when server fails

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#53]
# Criteria
In cases where we know what went wrong, we can provide specific messaging.
Svelte has a generic 500 error page (already added).

"we did something wrong"

500 Errors When server fails. Messaging / navigation may change depending on the particular error. See below

note: without blockchain, there will likely be less errors

## Tasks
~- [ ] error message & button: "something broke, please try again later" (we have to fix it first)~
~- [ ] definitely broken: "sorry something's not working" go back home. optional: ask for feedback~
~- [ ] nice to have: automatic retry~

- [x] catch-all for 500s: Retry (page refresh)

### Design
[View design specifications in figma ↗](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=681-276342&mode=design&t=v651aZ1nsmtaoKwC-4)

### Assets

- [x] [choodle-bob](https://www.notion.so/rmxparty/Error-page-graphics-aa1ea7f3e4e448be8f27bec6f716369d?pvs=4#8647e41c6d504b0cb8c8947eb9730511)
- [x] email help@rmx.party (see #93)
