### ISSUE TITLE
Users sees a welcome modal when they first land on choodle.xyz

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#58]
# Criteria
When user first lands on choodle.xyz, they should see a welcome modal with instructions on how to play. If user has already seen this modal, it should not pop-up.

**Question**
- [ ] is this a modal or a page?

## Tasks
~- [ ] if modal, set up basic modal component~
~- [ ] if modal, remember if user has seen the modal~
~- [ ] if modal, x: exit out of modal (if not a page)~
- [ ] title: Welcome to Choodle
- [ ] copy: how to play
- [ ] button: `Play`

## Design Reference
Design needs to determine if we're using a modal or window

![Image](https://github.com/rmx-party/choodle/assets/71292601/231a8dfd-b8c2-4bb5-85aa-44e340e4a929)
