### ISSUE TITLE
Prompt page: choodle of the day

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#59]
# Criteria
Before user draws, they see a "choodle of the day" page with a prompt to draw.

Prompts should change per given timeframe. To start: time frame will be 24 hours
Prompts will be text-only and uploaded beforehand via CMS

## Tasks
Page features:
- [ ] today's date
- [ ] title: "choodle of the day"
- [ ] block with prompt (to be connected to the CMS): text only
- [ ] CTA "GO": navigates to the canvas
- [ ] prompt set to change after a given time frame. To start: time will be daily, meaning prompt changes at midnight

![Image](https://github.com/rmx-party/choodle/assets/71292601/0c2fe0d2-8b1b-4093-9cf4-8ac9faf0c5fb)
