### ISSUE TITLE
When user selects 'Done' on the canvas, they see the viewChoodle page

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#63]
# Criteria
Give that the user has completed their choodle and press `Done` on the canvas, they are directed to the viewChoodle page and see the skeleton content. User should be able to share or save the image.

Note, this does not require styling. Rather, the layout should be adjusted and ensure that all buttons behave as expected

## Tasks
- [x] choodle image
- [x] some text
- [x] function to share, save, copy (native vs. built-in button)
finalizing tasks
- [x] Remove the `title` on the page
- [x] justify all content to be centered. Currently on reload, the content justifies left (I know you are working on this fix)
- [x] `make more choodles` should be a button that directs the user to a reset [blank] canvas
- [x] reset the canvas when selecting `make more choodles`
- [x] test for the share button to behave as expected (enable `save photo` option) see #78 
- [x] add copy below the image: `Save your Choodle as a photo, send it to a friend, and keep choodling.`

## Design Reference
Design WIP in Figma, [view here](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=522-328033&mode=design&t=WcyPbuxmZaoKeD49-11_)

_Note:_ For Sprint 1, we do not require FWB Fest info to be on the live prototype

![Image](https://github.com/rmx-party/choodle/assets/71292601/04a053b6-9b16-466f-a551-8855dd44fced)
