### ISSUE TITLE
Implement sharecard Open Graph metadata for all marketing pages including landing

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#7]
# Criteria
Utilizing Open Graph / Twitter Card sharecard standards, ensure any sharecard linked from choodle.xyz is ready for public-viewing

Ideally implemented in tandem with #19.

---

Updated tag info (July 21, 2023) by page:
- [x] **Landing page**
Title: Choodle
Link name: Welcome!
Image name: no name (hide)

- [x] **Canvas**
Title: Choodle
Link name: Choodle a doodle?
Image name: no name (hide)

- [x] **viewChoodle page**
Title: Choodle
Link name: Look, it’s a choodle
Image name: Choodle (but hide the name)

![Image](https://github.com/rmx-party/choodle/assets/71292601/d9ae36e5-5202-4562-bd20-8cf1137f7f41)

## Tasks
**metadata for landing sharecard:**
- [ ] images: [view in Notion](https://www.notion.so/rmxparty/0e7bf0d58fbd4545b7c2dcbc8fc5daeb?v=ec87388ffb1447ed9c7dd04ec365c8d3&pvs=4)
- [x] Title: `Choodle`
- [x] Description: `Draw something that lasts forever. Express yourself with lo-fi doodles that are yours to keep, sell, or share.`
- [x] url: choodle.xyz
- [x] type: website
- [ ] test appearance in different chat apps (twitter, discord, slack, signal, SMS)

### Design notes
* being able to share a link associated with their choodle image builds-in an opportunity for the receiver to then choodle themselves.
