### ISSUE TITLE
When user selects 'share' they see options to share via app or save to photos

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#78]
# Criteria
When a user selects the button `share` it opens the native options. For iOS, the options must show:
* save photo
* app options for sharing (e.g. SMS, airdrop, Instagram, signal, etc.)

When sharing, the content should include:
* the image
* title (that can be edited)

_note:_ what can be included with native sharing — files, title, description, and link. We may need to test how enabling each tag effects the default native options on iOS.

## Tasks
- [x] enable native option to save to photos
- [x] enable native option to share
- [x] when sharing, show the image and title (or, just the image)
