### ISSUE TITLE
As a user, I want tap a drawer, so that I can view 'how to choodle' in a drawer

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#89]
# Criteria
Given the 'how to choodle' content is on a drawer that lives over the canvas screen, interacting with the draw should have a couple interactions:

1. default state: user can see choodle logo & the prompt while they are drawing on the canvas
2. fully open: user can pull down from state 1 to see the full content of the drawer: instructions on how to choodle and the prompt
3. minimized state: user can tap/swipe up from state 1 to minimize the drawer as much as possible and only see the notch of the drawer

## Tasks
- [x] set up a slide/pull-down drawer over the canvas
- [x] start with tap to enable slide down
- [x] enable tap to slide back up
- [x] ~refinement: enable drag to enable slide down and back up:~ after Fest & in a separate ticket
- [x] depreciate the separate how-to-choodle page

## Design Reference
This is not final, but here is the [design reference](https://www.figma.com/file/wozIImqVXBLj3XbQH4tqCw/Choodle?type=design&node-id=537-412344&mode=design&t=yHRyGzrnlG2Txlx3-11) to start on the structure of the drawer

![Image](https://github.com/rmx-party/choodle/assets/71292601/984e2165-fc4d-4b56-824c-991c87b6199d)
